version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile.backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3000"
      - "9229:9229"

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile.frontend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
